#!/usr/bin/Rscript

#### Title: Numbat for melanoma paired samples (provide sample names as arguments)
#### Author: Jana Biermann, PhD

library(numbat)
library(dplyr)
library(Seurat)
library(ggplot2)
library(glue)
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(ggtree))
library(stringr)
library(tidygraph)
library(patchwork)
'%notin%' <- Negate('%in%')

pat1<- commandArgs()[6]
pat2<- commandArgs()[7]
pat<-strsplit(pat1,'_',fixed = T)[[1]][1]

mypal = c('1' = 'gray', '2' = "#377EB8", '3' = "#4DAF4A", '4' = "#984EA3", 
          '5'="#ff9768", '6'='#ae1717', '7'='#0f04b5', '8'="#f87382",
          '9'='green','10'='yellow','11'='deeppink','12'='black','13'='purple',
          '14'='yellow3','15'='deeppink3','16'='green3','17'='purple4','18'='blue2')

seu_all<-readRDS('data/merged/data_melanoma_merged_v2.rds')

# Get count_mat for pat
print(paste('Processing:', pat))
system(paste0('aws s3 cp s3://melanoma-ribas/numbat/',pat,'/',pat,'_allele_counts.tsv.gz data/',pat,'/ --quiet'))
seu<-subset(seu_all,sample==pat1 | sample==pat2)
dups<-seu$barcode_orig[which(duplicated(seu$barcode_orig))]
seu<-subset(seu, barcode_orig %notin% dups)
count_mat<-seu@assays$RNA@counts
colnames(count_mat)<-seu$barcode_orig

# Get ref_mat from entire cohort
ref_internal<-readRDS('data/tumor/numbat/data_numbat_melanoma_internal_ref.rds')

# allele dataframe generated by pileup_and_phase script
df_allele<-read.delim(paste0('data/',pat,'/',pat,'_allele_counts.tsv.gz'))
df_allele<- subset(df_allele,cell %in% seu$barcode_orig)

out = run_numbat(count_mat=count_mat, # gene x cell integer UMI count matrix 
                 lambdas_ref=ref_internal, # reference expression profile, a gene x cell type normalized expression level matrix
                 df_allele=df_allele, # allele dataframe generated by pileup_and_phase script
                 out_dir= paste0('data/',pat),
                 genome = "hg38",
                 ncores = 32,
                 plot = TRUE)


## Read numbat
nb = Numbat$new(out_dir = paste0('data/',pat))

# Single-cell CNV calls
cnv_calls<- nb$joint_post %>% select(cell, CHROM, seg, cnv_state, p_cnv, p_cnv_x, p_cnv_y)
table(cnv_calls$cnv_state,useNA = 'always')
cnv_calls %>% group_by(cnv_state) %>% arrange(p_cnv,desc=F)

# clone info
clones<-dim(table(nb$clone_post$clone_opt))
clone_info<-nb$clone_post
seu$cell<-seu$barcode_orig
seu$barcode_tmp<-rownames(seu@meta.data)
seu@meta.data<-left_join(seu@meta.data,clone_info,by='cell')
rownames(seu@meta.data)<-seu$barcode_tmp
saveRDS(seu,paste0("data/",pat,"/data_",pat,"_merged.rds"))

## Get clone segments
segs<- nb$segs_consensus
segs<- segs %>% group_by(seg_cons) %>% select(seg_cons, sample, CHROM,seg_start, seg_end, cnv_states)
segs$sample<-ifelse(is.na(segs$sample)==T,NA,paste0(pat,'_clone',segs$sample))
segs$pat_seg<-paste0(pat,'_seg',segs$seg_cons)
bulk<-nb$bulk_clones
bulk<-bulk %>% 
  select(seg_cons,logFC) %>% 
  na.omit() %>%
  group_by(seg_cons) %>%
  summarise(log2FC_median = median(logFC),
            log2FC_mean = mean(logFC))
segs<-left_join(segs,bulk,by='seg_cons')
write.csv(segs,paste0("data/",pat,"/table_",pat,"_segs.csv"),row.names = F)

clon<- clone_info %>% select(cell, clone_opt, GT_opt)
write.csv(clon,paste0("data/",pat,"/table_",pat,"_clone.csv"),row.names = F)


# plots
pdf(paste0("data/",pat,"/plots_",pat,"_numbat.pdf"),width = 10)
# Copy number landscape and single-cell phylogeny
nb$plot_phylo_heatmap(clone_bar = TRUE, p_min = 0.9,raster = T,pal_clone = mypal)

# Consensus copy number segments
nb$plot_consensus()

# Bulk CNV profiles
nb$bulk_clones %>% 
  filter(n_cells > 50) %>%
  plot_bulks(min_LLR = 10, # filtering CNVs by evidence
             legend = TRUE,raster=T)

# clones
DimPlot(seu, group.by = 'clone_opt',shuffle = T, raster=T,cols = mypal[1:clones],
        pt.size = 2)+coord_fixed()
DimPlot(seu, group.by = 'GT_opt',shuffle = T, raster=T,
        pt.size = 2)+coord_fixed()
DimPlot(seu, group.by = 'sample',shuffle = T, raster=T,
        pt.size = 2)+coord_fixed()
DimPlot(seu, group.by = 'celltype_bped_main',shuffle = T, raster=T,
        pt.size = 2)+coord_fixed()
DimPlot(seu, group.by = 'malignant',shuffle = T, raster=T,
        pt.size = 2)+coord_fixed()+ggtitle('inferCNV malignant')

seu$clone_opt<-as.factor(seu$clone_opt)
p01<-ggplot(as.data.frame(seu@meta.data), aes(x = sample, fill = clone_opt))+
  geom_bar(stat="count",col='black')+
  theme_classic()+
  ggtitle('Clone distribution') + 
  ylab('Cell numbers of clones')+
  scale_fill_manual(values = mypal[1:clones])+
  theme(legend.position = 'right', 
        axis.title.x = element_blank(), 
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

p02<-ggplot(as.data.frame(seu@meta.data), aes(x = sample, fill = clone_opt)) + 
  geom_bar(position = 'fill', stat="count",col='black') + 
  theme_classic() + 
  ggtitle('Clone distribution') + 
  ylab('Fraction of clones')+
  scale_fill_manual(values = mypal[1:clones])+
  theme(legend.position = 'right', 
        axis.title.x = element_blank(), 
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

p03<-ggplot(as.data.frame(seu@meta.data %>% filter(clone_opt %in% c(2:clones))), 
            aes(x = sample, fill = clone_opt)) + 
  geom_bar(position = 'fill', stat="count",col='black') + 
  theme_classic() + 
  ggtitle('Clone distribution (only tumor cells)') + 
  ylab('Fraction of clones')+
  scale_fill_manual(values = mypal[1:clones])+
  theme(legend.position = 'right', 
        axis.title.x = element_blank(), 
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
print(p01+p02+p03)

# Tumor versus normal probability
p1<-FeaturePlot(seu, features  = c('p_cnv'),order = F, raster=T,pt.size = 2)+
  coord_fixed()+
  scale_color_gradient2(low = 'royalblue', mid = 'white', high = 'red3', midpoint = 0.5, name = 'Posterior')+
  ggtitle('Tumor vs normal probability\n(joint)')

p2<-FeaturePlot(seu, features  = c('p_cnv_x'),order = F, raster=T,pt.size = 2)+
  coord_fixed()+
  scale_color_gradient2(low = 'royalblue', mid = 'white', high = 'red3', midpoint = 0.5,name = 'Posterior')+
  ggtitle('Tumor vs normal probability\n(gex)')

p3<-FeaturePlot(seu, features  = c('p_cnv_y'),order = F, raster=T,pt.size = 2)+
  coord_fixed()+
  scale_color_gradient2(low = 'royalblue', mid = 'white', high = 'red3', midpoint = 0.5, name = 'Posterior')+
  ggtitle('Tumor vs normal probability\n(allele)')
print((p1+p2 +p3)+plot_layout(ncol=2))

# Tumor phylogeny
nb$plot_sc_tree(
  label_size = 3, 
  branch_width = 0.5, 
  tip_length = 0.5,
  pal_clone = mypal,
  tip = TRUE)

# mutational history
nb$plot_mut_history(pal=mypal)
dev.off()

system(paste0("aws s3 sync data/",pat,"/ s3://melanoma-ribas/numbat/",pat,"/ --exclude '*_cnv.rds' --quiet"))
print(paste('Finished:', pat))
